services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"   # porta_do_host:porta_do_container
    environment:
      - NODE_ENV=production
    restart: always   # reinicia automaticamente se cair